[package]
name = "xbattery"
version = "0.3.1"
edition = "2024"

[workspace]
members = [".", "xtask"]
default-members = ["."]

[dependencies]
clap = { version = "4.5", default-features = false, features = [
	"derive",
	"error-context",
	"help",
	"std",
	"usage",
] }
ctrlc = "3.5.2"
serde = { version = "1.0.219", features = ["derive"] }
self_update = { version = "0.44", default-features = false, features = [
	"archive-zip",
	"compression-zip-deflate",
	"rustls",
	"ureq",
] }
toml = "0.8.23"
windows = { version = "0.62.2", features = [
	"Data_Xml_Dom",
	"Devices_Power",
	"Foundation",
	"Foundation_Collections",
	"Gaming_Input",
	"Win32_Media_Audio",
	"UI_Notifications",
	"Win32_Foundation",
	"Win32_Security",
	"Win32_System_Com",
	"Win32_System_Console",
	"Win32_System_Diagnostics_ToolHelp",
	"Win32_System_Threading",
	"Win32_UI_Input_XboxController",
	"Win32_UI_Shell",
	"Win32_UI_WindowsAndMessaging",
] }

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
incremental = false
codegen-units = 1
