# Default xbattery configuration.

[monitor]
poll_interval_seconds = 60
control_wait_slice_millis = 250

[battery.levels.full]
threshold_percent = 100
coarse_level = "full"
notify = false
urgent = false

[battery.levels.medium]
threshold_percent = 70
coarse_level = "medium"
notify = true
urgent = false

[battery.levels.low]
threshold_percent = 40
coarse_level = "low"
notify = true
urgent = false

[battery.levels.empty]
threshold_percent = 10
coarse_level = "empty"
notify = true
urgent = true

[notifications]
app_id = "xbattery"
notify_connected = true
notify_disconnected = true

[updates]
repo_owner = "F0903"
repo_name = "xbattery"
asset_identifier = "xbattery"
bin_path_in_archive = "xbattery.exe"
check_automatically = true
check_interval_hours = 24
auto_install = false
notify_available = true
